databases:
  - name: chat-pilot
    plan: free
    user: shreshth

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: GROQ_API_KEY
      - key: NOMIC_API_KEY